ALTER TYPE analysis_status ADD VALUE IF NOT EXISTS 'PREPROCESSING_COMPLETED';
ALTER TYPE analysis_status ADD VALUE IF NOT EXISTS 'AI_QUEUED';
ALTER TYPE analysis_status ADD VALUE IF NOT EXISTS 'AI_PROCESSING';
ALTER TYPE analysis_status ADD VALUE IF NOT EXISTS 'AI_COMPLETED';

ALTER TYPE analysis_request_status ADD VALUE IF NOT EXISTS 'PREPROCESSING_COMPLETED';
ALTER TYPE analysis_request_status ADD VALUE IF NOT EXISTS 'AI_PROCESSING';